package com.cmdhelper.drfun;

public class CommandList {
    public static Object[] commandList() {
        Object[] commandlist = new Object[]{
                "?",
                "ability",
                "alwaysday",
                "camerashake",
                "changesetting",
                "clear",
                "clearspawnpoint",
                "clone",
                "connect",
                "damage",
                "daylock",
                "dedicatedwsserver",
                "deop",
                "difficulty",
                "effect",
                "enchant",
                "event",
                "execute",
                "fill",
                "fog",
                "function",
                "gamemode",
                "gamerule",
                "gametest",
                "give",
                "help",
                "immutableworld",
                "kick",
                "kill",
                "list",
                "locate",
                "loot",
                "me",
                "mobevent",
                "msg",
                "music",
                "op",
                "ops",
                "particle",
                "permission",
                "playanimation",
                "playsound",
                "reload",
                "replaceitem",
                "ride",
                "save",
                "say",
                "schedule",
                "scoreboard",
                "setblock",
                "setmaxplayers",
                "setworldspawn",
                "spawnpoint",
                "spreadplayers",
                "stop",
                "stopsound",

        };
        return commandlist;
    }
}
