package com.cmdhelper.drfun.Util;

import org.jetbrains.annotations.Contract;

public class CommandList {
    @Contract(pure = true)
    public static Object[] commandList() {
        return new Object[]{
                "?",
                "ability",
                "alwaysday",
                "camerashake",
                "changesetting",
                "clear",
                "clearspawnpoint",
                "clone",
                "connect",
                "damage",
                "daylock",
                "dedicatedwsserver",
                "deop",
                "difficulty",
                "effect",
                "enchant",
                "event",
                "execute",
                "fill",
                "fog",
                "function",
                "gamemode",
                "gamerule",
                "gametest",
                "give",
                "help",
                "immutableworld",
                "kick",
                "kill",
                "list",
                "locate",
                "loot",
                "me",
                "mobevent",
                "msg",
                "music",
                "op",
                "ops",
                "particle",
                "permission",
                "playanimation",
                "playsound",
                "reload",
                "replaceitem",
                "ride",
                "save",
                "say",
                "schedule",
                "scoreboard",
                "setblock",
                "setmaxplayers",
                "setworldspawn",
                "spawnpoint",
                "spreadplayers",
                "stop",
                "stopsound",
                "structure",
                "summon",
                "tag",
                "teleport",
                "tell",
                "tellraw",
                "testfor",
                "testforblock",
                "testforblocks",
                "tickingarea",
                "time",
                "title",
                "titleraw",
                "toggledownfall",
                "tp",
                "volumearea",
                "w",
                "wb",
                "weather",
                "whitelist",
                "worldbuilder",
                "wsserver",
                "xp",
        };
    }

    public static Object[] commandTargetSelector() {
        return new Object[]{
                "@p",
                "@s",
                "@a",
                "@r",
                "@e",
                "@c", // Education Edition only
                "@v", // Education Edition only
                "@initiator", // BedrockEdition only
        };
    }

    public static Object[] commandTargetSelectorParameters() {
        return new Object[]{
                "x",
                "y",
                "z",
                "r",
                "rm",
                "dx",
                "dy",
                "dz",
                "scores",
                "tag",
                "name",
                "type",
                "family",
                "rx",
                "rxm",
                "ry",
                "rym",
                "hasitem",
                "l",
                "lm",
                "m",
                "c",
        };
    }
}